from pathlib import Path

GENERATED_TESTS_DIR = "generated_tests"

CONFTEST_TEMPLATE = '''import pytest
import os


@pytest.fixture(scope="session")
def base_url():
    return os.getenv("BASE_URL", "{base_url}")


@pytest.fixture(scope="session")
def headers():
    token = os.getenv("API_TOKEN", "")
    if token:
        return {{"Content-Type": "application/json", "x-api-key": token}}
    return {{"Content-Type": "application/json"}}


@pytest.fixture(scope="session")
def auth_headers(headers):
    return headers
'''

FILE_HEADER = '"""\nAuto-generated by AI API Test Suite Generator\nhttps://github.com/Maiitarek/ai-api-test-generator\n"""\nimport pytest\nimport requests\nimport allure\n\n\n'


def write_generated_tests(test_code_map: dict, base_url: str, output_dir: str = GENERATED_TESTS_DIR):
    output_path = Path(output_dir)
    output_path.mkdir(exist_ok=True)
    with open(output_path / "conftest.py", "w", encoding="utf-8") as f:
        f.write(CONFTEST_TEMPLATE.format(base_url=base_url))
    (output_path / "__init__.py").touch()
    written = []
    for filename, code in test_code_map.items():
        file_path = output_path / filename
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(FILE_HEADER + code)
        written.append(str(file_path))
        print(f"  Written: {file_path}")
    return written


def clean_generated_tests(output_dir: str = GENERATED_TESTS_DIR):
    output_path = Path(output_dir)
    if output_path.exists():
        for f in output_path.glob("test_*.py"): f.unlink()
        conftest = output_path / "conftest.py"
        if conftest.exists(): conftest.unlink()
        print(f"Cleaned {output_dir}/")
